services:
    _defaults:
        public: true
        
    CoreShop\Payum\UnzerBundle\Form\Payment\UnzerType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: unzer }
            - { name: form.type }

    payum.unzer_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [CoreShop\Payum\Unzer\UnzerGatewayFactory]
        tags:
            - {name: payum.gateway_factory_builder, factory: unzer }

    CoreShop\Payum\UnzerBundle\Extension\PopulateUnzerExtension:
        autowire: true
        tags:
            - { name: payum.extension, alias: unzer_populate, factory: unzer, gateway: unzer, prepend: false }

    CoreShop\Payum\UnzerBundle\Extension\ObtainTokenExtension:
        autowire: true
        tags:
            - { name: payum.extension, alias: unzer_obtain_token, factory: unzer, gateway: unzer, prepend: false }
